openapi: 3.2.0
info:
  title: Fusion Admin Scheduler API
  description: These APIs provide general administrative functions for your Fusion instance. Use these APIs to manage Fusion objects, App Studio objects, connections to Solr clusters, license files, job schedules, and more. You can also use them to create a history of service events.
  termsOfService: https://lucidworks.com/legal/developer-license-agreement/
  contact:
    name: Lucidworks
    url: www.lucidworks.com
    email: support@lucidworks.com
  license:
    name: License of API
    url: https://lucidworks.com/legal/developer-license-agreement/
  version: '5.9'
servers:
- url: https://{FUSION HOST}/api
  description: Fusion
  variables:
    FUSION HOST:
      default: FUSION_HOST
      description: Your environment host.
- url: https://{FUSION HOST}/api/apps/{APP_NAME}
  description: Fusion app
  variables:
    FUSION HOST:
      default: FUSION_HOST
      description: Your environment host.
    APP_NAME:
      default: APP_NAME
      description: The name of your Fusion application.
tags:
- name: Scheduler
  description: 'Use the Scheduler API to define a schedule for system activities and manage the jobs that result from the schedule. All of the Fusion services are available for scheduling, as are any Solr activities and any other HTTP-based URI.


    >This API is deprecated in favor of the Jobs API.'
paths:
  /scheduler/status:
    get:
      tags:
      - Scheduler
      summary: Get scheduler service status
      description: Check the status of the Scheduler service.
      operationId: getStatus_18
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceStatus'
  /scheduler/jobs:
    get:
      tags:
      - Scheduler
      summary: List all running jobs
      description: List all currently-running jobs.
      operationId: getRunningJobs
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
              example:
              - id: '2'
                trigger: 2_1400011854443_-9223372036854775807
                schedule:
                  id: '2'
                  creatorType: human
                  creatorId: admin1
                  createTime: '2014-05-13T20:10:54.443Z'
                  startTime: '2014-05-13T20:10:54.443Z'
                  endTime: null
                  repeatUnit: HOUR
                  interval: 1
                  active: true
                  callParams:
                    uri: solr://demo/update
                    method: GET
                    queryParams:
                      stream.body: <commit/>
                    headers: {}
                    entity: null
              - id: '1'
                trigger: 1_1400007488512_-9223372036854775808
                schedule:
                  id: '1'
                  creatorType: human
                  creatorId: admin1
                  createTime: '2014-05-13T18:58:08.512Z'
                  startTime: '2014-05-13T18:58:08.512Z'
                  endTime: null
                  repeatUnit: DAY
                  interval: 1
                  active: true
                  callParams:
                    uri: service://connectors/jobs/LocalDocs2
                    method: POST
                    queryParams: {}
                    headers: {}
                    entity: null
    delete:
      tags:
      - Scheduler
      summary: Stop all running jobs
      description: Stop all currently-running jobs.
      operationId: stopRunningJobs
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /scheduler/jobs/{id}:
    get:
      tags:
      - Scheduler
      summary: Get a scheduled job
      description: Fetch details about a scheduled job.
      operationId: getRunningJob
      parameters:
      - name: id
        in: path
        description: The schedule ID.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  properties: {}
    delete:
      tags:
      - Scheduler
      summary: Stop a running job
      description: Stop a currently-running job.
      operationId: stopRunningJob
      parameters:
      - name: id
        in: path
        description: The schedule ID.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content: {}
  /scheduler/schedules:
    get:
      tags:
      - Scheduler
      summary: List matching schedules
      description: Fetch the list of all matching schedules.
      operationId: getSchedules
      parameters:
      - name: creatorType
        in: query
        description: The type of user that created the schedule.
        schema:
          type: string
      - name: creatorId
        in: query
        description: The ID of the user that created the schedule.
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Schedule'
    post:
      tags:
      - Scheduler
      summary: Create a schedule
      description: Create a new schedule.
      operationId: addSchedule
      requestBody:
        description: JSON-formatted schedule configuration values.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schedule'
            example:
              id: '1'
              creatorType: human
              creatorId: admin1
              repeatUnit: DAY
              interval: 1
              active: true
              callParams:
                uri: service://connectors/jobs/LocalDocs2
                method: POST
        required: false
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
              example:
                id: '1'
                trigger: 1_1400007488512_-9223372036854775808
                schedule:
                  id: '1'
                  creatorType: human
                  creatorId: admin1
                  createTime: '2014-05-13T18:58:08.512Z'
                  startTime: '2014-05-13T18:58:08.512Z'
                  endTime: null
                  repeatUnit: DAY
                  interval: 1
                  active: true
                  callParams:
                    uri: service://connectors/jobs/LocalDocs2
                    method: POST
                    queryParams: {}
                    headers: {}
                    entity: null
      x-codegen-request-body-name: body
    delete:
      tags:
      - Scheduler
      summary: Delete schedules
      description: Delete schedules that match a creator ID or type.
      operationId: deleteSchedules
      parameters:
      - name: creatorType
        in: query
        description: The type of user that created the schedule.
        schema:
          type: string
      - name: creatorId
        in: query
        description: The ID of the user that created the schedule.
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /scheduler/schedules/{id}:
    get:
      tags:
      - Scheduler
      summary: Get a schedule
      description: Fetch the specified schedule.
      operationId: getSchedule
      parameters:
      - name: id
        in: path
        description: The schedule ID.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
    put:
      tags:
      - Scheduler
      summary: Update a schedule
      description: Update a schedule's configuration.
      operationId: updateSchedule
      parameters:
      - name: id
        in: path
        description: The schedule ID.
        required: true
        schema:
          type: string
      requestBody:
        description: JSON-formatted schedule configuration values.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schedule'
            example:
              creatorType: human
              creatorId: admin1
              repeatUnit: HOUR
              interval: 1
              active: false
              callParams:
                uri: solr://demo/update
                method: GET
                queryParams:
                  stream.body: <commit/>
        required: false
      responses:
        '200':
          description: successful operation
          content: {}
      x-codegen-request-body-name: body
    delete:
      tags:
      - Scheduler
      summary: Delete a schedule
      description: Delete a schedule by ID.
      operationId: deleteSchedule
      parameters:
      - name: id
        in: path
        description: The schedule ID.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content: {}
components:
  schemas:
    Schedule:
      type: object
      properties:
        id:
          type: string
          description: The ID of the schedule. This is required when creating a schedule with a POST request.
        creatorType:
          type: string
          description: The type of user that created the schedule. If you have resources creating schedules programmatically, you could define a type that helps distinguish those schedules from others created by people.
        creatorId:
          type: string
          description: An ID for the user that created the schedule.
        createTime:
          type: string
          format: date-time
        startTime:
          type: string
          description: A time when the schedule should be started. If this is not set, it will be set to the date/time when the schedule was created.
          format: date-time
        endTime:
          type: string
          description: A time when the schedule should be terminated, i.e., when it will not run any more in the future. If not set, the schedule will run until it is disabled (i.e., `active` is set to `false`) or deleted.
          format: date-time
        repeatUnit:
          type: string
          description: 'A unit of time that when combined with the interval property defines how often the schedule will run. Allowed values are: <br/>● `millisecond` or `ms`<br/>● `second` or `sec`<br/>● `minute` or `min`<br/>● `hour` or `hr`<br/>● `day`<br/>● `week`<br/>● `month`  These time units are not case-sensitive.'
          enum:
          - MILLISECOND
          - SECOND
          - MINUTE
          - HOUR
          - DAY
          - WEEK
          - MONTH
        interval:
          type: integer
          description: An integer that when combined with the repeatUnit property defines how often the schedule will run. If this is not set, or set to a number lower than '1' (i.e., '0'), the schedule will only be run once.
          format: int32
        active:
          type: boolean
          description: If **true**, the schedule will be executed according to the defined interval. If **false**, the schedule will be disabled and will not run at the defined time.
        callParams:
          $ref: '#/components/schemas/CallParams'
    ServiceStatus:
      type: object
      properties:
        status:
          type: string
          enum:
          - starting
          - ok
          - warning
          - error
          - shutdown
        node:
          type: string
          readOnly: true
        messages:
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/StatusMessage'
    StatusMessage:
      type: object
      properties:
        date:
          type: string
          format: date-time
          readOnly: true
        message:
          type: string
          readOnly: true
    CallParams:
      type: object
      properties:
        uri:
          type: string
          description: 'A fully-qualified service URI. This can be an HTTP call, a Solr request, or a Managed Fusion service call. <br/>Supported URI schemas are: `http://`, `https://`, `solr://{collection}/…​`, or `service://{serviceName}/{path}`.'
        method:
          type: string
          enum:
          - GET
          - PUT
          - POST
          - DELETE
        queryParams:
          type: object
          description: Query parameters to be passed with the request. For Solr calls, this could be parameters such as `q`, `fq`, `commit`, and so on
          additionalProperties:
            type: string
        headers:
          type: object
          description: Any additional protocol headers, such as `Content-type`.
          additionalProperties:
            type: string
        entity:
          type: object
          description: An optional payload to be sent with the request.
          properties: {}
  securitySchemes:
    Basic_auth:
      type: http
      scheme: basic
    API_key:
      name: x-api-key
      type: apiKey
      in: header
x-original-swagger-version: '2.0'
